<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use App\Models\User;
use App\Models\Post;
use App\Models\Category;
use App\Models\Tag;

class ResetScrapedData extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:reset-scraped-data';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Resets scraped posts, categories, tags, and autogenerated authors.';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        if (!$this->confirm('Are you sure you want to reset all scraped data? This will delete all Posts, Categories, Tags, and autogenerated Authors.')) {
            $this->info('Aborted.');
            return;
        }

        $this->info('Disabling foreign key checks...');
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        $this->info('Truncating pivots...');
        DB::table('category_post')->truncate();
        DB::table('post_tag')->truncate();
        DB::table('comments')->truncate();
        DB::table('likes')->truncate();

        $this->info('Truncating main contents...');
        Post::truncate();
        Category::truncate();
        Tag::truncate();

        $this->info('Deleting generated authors (users without admin role)...');
        // Delete all users except for the main admins. Ensure we don't accidentally remove actual team members
        // For safety, let's delete users that don't have 'admin' role, or you can tailor this to only specific imported users.
        $deletedUsers = User::where('role', '!=', 'admin')->delete();
        $this->info("Deleted $deletedUsers autogenerated users.");

        $this->info('Enabling foreign key checks...');
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->info('All scraped data has been successfully reset. Ready for a fresh import!');
    }
}
